name: marybirdsong
favicon: null
layout_spectrum: 0.26326494943350554
typography_spectrum: 0.8038326008245349
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#020202'
    - '#acacac'
    - '#2f2f2f'
    - '#fefefe'
    - '#6f6f6f'
  brandStrength: 0.5
  lightness: 0.620873583946377
  saturation: 0.1875
  rhythmicContrast: 0.5
purpose: []
